// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvuy7-v07l31in26ZV6RA12YSd8hWi1E',
    appId: '1:445343032164:web:e9b7c501fc09a53ac51071',
    messagingSenderId: '445343032164',
    projectId: 'lab3mis-712eb',
    authDomain: 'lab3mis-712eb.firebaseapp.com',
    storageBucket: 'lab3mis-712eb.firebasestorage.app',
    measurementId: 'G-FDFTZVVBWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9arPlraXdpKLx3miK8EcGuORk-8DMnK0',
    appId: '1:445343032164:android:1c41d13abcded057c51071',
    messagingSenderId: '445343032164',
    projectId: 'lab3mis-712eb',
    storageBucket: 'lab3mis-712eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EwQ6xFMbnh2Oyptqwo26awpO4WQ9uRE',
    appId: '1:445343032164:ios:ee76510772dcaf33c51071',
    messagingSenderId: '445343032164',
    projectId: 'lab3mis-712eb',
    storageBucket: 'lab3mis-712eb.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5EwQ6xFMbnh2Oyptqwo26awpO4WQ9uRE',
    appId: '1:445343032164:ios:ee76510772dcaf33c51071',
    messagingSenderId: '445343032164',
    projectId: 'lab3mis-712eb',
    storageBucket: 'lab3mis-712eb.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfvuy7-v07l31in26ZV6RA12YSd8hWi1E',
    appId: '1:445343032164:web:5411a4feb7ca6fa9c51071',
    messagingSenderId: '445343032164',
    projectId: 'lab3mis-712eb',
    authDomain: 'lab3mis-712eb.firebaseapp.com',
    storageBucket: 'lab3mis-712eb.firebasestorage.app',
    measurementId: 'G-K3TJ156GMD',
  );

}